<a href="https://colab.research.google.com/github/madanjha/Machine-Learning/blob/main/DimensionaltyReduction_Self.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [27]:

url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names=['sepal-length','sepal-width','petal-length','petal-width','Class']
dataset=pd.read_csv(url,names=names)

In [28]:
dataset.head()

,sepal-length,sepal-width,petal-length,petal-width,Class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa


In [29]:
X = dataset.drop('Class',axis=1)
y = dataset['Class']

In [30]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [31]:
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [32]:
pca=PCA()
X_train=pca.fit_transform(X_train)
X_test=pca.transform(X_test)

In [33]:
explain_variance=pca.explained_variance_ratio_

In [35]:
def perform_pca(n):
    X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2,random_state=0)
    pca=PCA(n_components=n)
    pca_x_train=pca.fit_transform(X_train)
    pca_x_test=pca.transform(X_test)
    classifier=RandomForestClassifier(max_depth=2,random_state=0)
    classifier.fit(pca_x_train,y_train)
    y_pred=classifier.predict(pca_x_test)
    cm=confusion_matrix(y_test,y_pred)
    print(cm)
    print('Accuracy {0}\n\n'.format(accuracy_score(y_test,y_pred)))

In [36]:
for i in range(1,5):
    perform_pca(i)

[[11  0  0]
 [ 0 12  1]
 [ 0  2  4]]
Accuracy 0.9


[[11  0  0]
 [ 0  8  5]
 [ 0  1  5]]
Accuracy 0.8


[[11  0  0]
 [ 0  5  8]
 [ 0  1  5]]
Accuracy 0.7


[[11  0  0]
 [ 0 11  2]
 [ 0  1  5]]
Accuracy 0.9


